pull_request_rules:
  - name: Automatically merge Renovate PRs
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - author = renovate[bot]
    actions:
      merge:
