# See https://github.com/greshake/i3status-rust/blob/master/blocks.md
# vi:syntax=toml

#theme = "solarized-dark"
#theme = "slick"
# icons = "awesome"
#icons = "material"

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Default Dark by Chris Kempson (http://chriskempson.com)
# theme = "solarized-dark"

# FIXME: Not working anymore
# [theme.overrides]
# idle_bg = "#181818"
# idle_fg = "#d8d8d8"
# info_bg = "#86c1b9"
# info_fg = "#181818"
# good_bg = "#a1b56c"
# good_fg = "#181818"
# warning_bg = "#f7ca88"
# warning_fg = "#181818"
# critical_bg = "#ab4642"
# critical_fg = "#181818"
# The rest of the theme settings are left at default.

#https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"

[[block]]
block = "load"
interval = 1

[[block]]
block = "net"
device = "wlp4s0"
# ssid = true
#ip = true
# speed_up = false
# graph_up = true
interval = 5

# [[block]]
# block = "music"
# player = "spotify"
# buttons = ["play", "next"]

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10

[[block]]
block = "time"
interval = 60
