# Build and deploy MkDocs to gh-pages for main branch
name: gh-pages
on:
  check_suite:
    types: [completed]

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.check_suite.head_sha }}

      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          extra_nix_config: |
            substituters = https://cache.garnix.io
            trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Build the docs
        id: build
        run: |
          nix build .#docs
          echo "result=$(readlink ./result)" >> $GITHUB_OUTPUT
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ steps.build.outputs.result }}/"
